In [1]:
import os
os.chdir("..")
%pwd

'/Users/beamaia/Documents/ndb_ufes_data_organizer'

In [37]:
import pandas as pd
import pathlib as pl

## Get ids

In [ ]:
missing_ids = pd.read_csv("missing_ids.csv")
wrong_ids = pd.read_csv("wrong_ids.csv")

In [4]:
missing_ids.head()

   missing_patch_id  origin
0                 3      -1
1                10      -1
2                12      -1
3                38      -1
4                39      -1

In [5]:
wrong_ids.head()

   patch  correct_origin
0  p0011            -1.0
1  p0227            18.0
2  p0230            18.0
3  p0281           156.0
4  p0285           156.0

In [6]:
unknown_origin_wrong_ids = wrong_ids[wrong_ids["correct_origin"] == -1]

In [8]:
unknown_origin_wrong_ids.head()

    patch  correct_origin
0   p0011            -1.0
20  p0870            -1.0
21  P0872            -1.0
22  p0873            -1.0
23  p0874            -1.0

In [9]:
len(unknown_origin_wrong_ids)

78

In [10]:
len(missing_ids)

561

In [12]:
missing_ids["patch"] = missing_ids["missing_patch_id"].apply(lambda x: f"p{x:04}" )

In [23]:
missing_ids = missing_ids.drop(columns=["missing_patch_id"])
unknown_origin_wrong_ids = unknown_origin_wrong_ids.reset_index(drop=True)
unknown_origin_wrong_ids["origin"] = -1
unknown_origin_wrong_ids = unknown_origin_wrong_ids.drop(columns=["correct_origin"])

In [34]:
all_missing_ids = pd.concat([missing_ids, unknown_origin_wrong_ids], axis=0)
all_missing_ids["patch"] = all_missing_ids["patch"].apply(lambda x: x.lower())
all_missing_ids = all_missing_ids.sort_values(by=["patch"])
all_missing_ids = all_missing_ids.reset_index(drop=True)

In [35]:
all_missing_ids.head()

   origin  patch
0      -1  p0003
1      -1  p0010
2      -1  p0011
3      -1  p0012
4      -1  p0038

In [36]:
all_missing_ids

     origin  patch
0        -1  p0003
1        -1  p0010
2        -1  p0011
3        -1  p0012
4        -1  p0038
..      ...    ...
634      -1  p3691
635      -1  p3692
636      -1  p3726
637      -1  p3743
638      -1  p3761

[639 rows x 2 columns]

In [49]:
DATA_PATH = pl.Path("data/ndb_ufes/patch/images")
images_paths = sorted([img.name.split(".")[0] for img in DATA_PATH.glob("*.png")])

In [54]:
for row in all_missing_ids.iterrows():
    patch = row[1]["patch"]

    if patch in images_paths:
        print(f"Patch {patch} is present")
        all_missing_ids.at[row[0], "path"] = DATA_PATH / f"{patch}.png"

Patch p0003 is present
Patch p0010 is present
Patch p0011 is present
Patch p0012 is present
Patch p0038 is present
Patch p0039 is present
Patch p0040 is present
Patch p0041 is present
Patch p0057 is present
Patch p0126 is present
Patch p0127 is present
Patch p0128 is present
Patch p0129 is present
Patch p0130 is present
Patch p0131 is present
Patch p0132 is present
Patch p0133 is present
Patch p0158 is present
Patch p0159 is present
Patch p0160 is present
Patch p0161 is present
Patch p0162 is present
Patch p0163 is present
Patch p0164 is present
Patch p0313 is present
Patch p0314 is present
Patch p0315 is present
Patch p0316 is present
Patch p0317 is present
Patch p0318 is present
Patch p0319 is present
Patch p0320 is present
Patch p0432 is present
Patch p0433 is present
Patch p0434 is present
Patch p0435 is present
Patch p0436 is present
Patch p0437 is present
Patch p0438 is present
Patch p0439 is present
Patch p0554 is present
Patch p0571 is present
Patch p0638 is present
Patch p0639 is present
Patch p0640 is present
Patch p0641 is present
Patch p0642 is present
Patch p0643 is present
Patch p0644 is present
Patch p0645 is present
Patch p0646 is present
Patch p0647 is present
Patch p0648 is present
Patch p0649 is present
Patch p0650 is present
Patch p0651 is present
Patch p0652 is present
Patch p0653 is present
Patch p0654 is present
Patch p0655 is present
Patch p0656 is present
Patch p0657 is present
Patch p0658 is present
Patch p0659 is present
Patch p0660 is present
Patch p0661 is present
Patch p0662 is present
Patch p0663 is present
Patch p0664 is present
Patch p0665 is present
Patch p0666 is present
Patch p0667 is present
Patch p0668 is present
Patch p0713 is present
Patch p0714 is present
Patch p0715 is present
Patch p0716 is present
Patch p0717 is present
Patch p0718 is present
Patch p0719 is present
Patch p0785 is present
Patch p0786 is present
Patch p0787 is present
Patch p0788 is present
Patch p0789 is present
Patch p0790 is present
Patch p0791 is present
Patch p0792 is present
Patch p0793 is present
Patch p0794 is present
Patch p0870 is present
Patch p0871 is present
Patch p0872 is present
Patch p0873 is present
Patch p0874 is present
Patch p0875 is present
Patch p0876 is present
Patch p0877 is present
Patch p0878 is present
Patch p0879 is present
Patch p0880 is present
Patch p0881 is present
Patch p0882 is present
Patch p0883 is present
Patch p0884 is present
Patch p0885 is present
Patch p0892 is present
Patch p0893 is present
Patch p0894 is present
Patch p0895 is present
Patch p0896 is present
Patch p0897 is present
Patch p0898 is present
Patch p0899 is present
Patch p0900 is present
Patch p0901 is present
Patch p0902 is present
Patch p0903 is present
Patch p0904 is present
Patch p0905 is present
Patch p0906 is present
Patch p0946 is present
Patch p0947 is present
Patch p0948 is present
Patch p0966 is present
Patch p0997 is present
Patch p0998 is present
Patch p0999 is present
Patch p1000 is present
Patch p1001 is present
Patch p1002 is present
Patch p1017 is present
Patch p1018 is present
Patch p1078 is present
Patch p1137 is present
Patch p1138 is present
Patch p1139 is present
Patch p1162 is present
Patch p1172 is present
Patch p1173 is present
Patch p1174 is present
Patch p1175 is present
Patch p1192 is present
Patch p1265 is present
Patch p1266 is present
Patch p1267 is present
Patch p1268 is present
Patch p1269 is present
Patch p1270 is present
Patch p1271 is present
Patch p1272 is present
Patch p1273 is present
Patch p1274 is present
Patch p1275 is present
Patch p1276 is present
Patch p1277 is present
Patch p1278 is present
Patch p1279 is present
Patch p1280 is present
Patch p1281 is present
Patch p1282 is present
Patch p1283 is present
Patch p1284 is present
Patch p1285 is present
Patch p1286 is present
Patch p1287 is present
Patch p1324 is present
Patch p1325 is present
Patch p1326 is present
Patch p1378 is present
Patch p1379 is present
Patch p1380 is present
Patch p1381 is present
Patch p1382 is present
Patch p1383 is present
Patch p1384 is present
Patch p1385 is present
Patch p1386 is present
Patch p1387 is present
Patch p1388 is present
Patch p1453 is present
Patch p1456 is present
Patch p1457 is present
Patch p1458 is present
Patch p1459 is present
Patch p1460 is present
Patch p1461 is present
Patch p1462 is present
Patch p1463 is present
Patch p1464 is present
Patch p1465 is present
Patch p1466 is present
Patch p1469 is present
Patch p1470 is present
Patch p1471 is present
Patch p1472 is present
Patch p1473 is present
Patch p1474 is present
Patch p1475 is present
Patch p1476 is present
Patch p1477 is present
Patch p1478 is present
Patch p1502 is present
Patch p1503 is present
Patch p1504 is present
Patch p1505 is present
Patch p1506 is present
Patch p1507 is present
Patch p1508 is present
Patch p1509 is present
Patch p1510 is present
Patch p1511 is present
Patch p1512 is present
Patch p1513 is present
Patch p1562 is present
Patch p1569 is present
Patch p1570 is present
Patch p1574 is present
Patch p1575 is present
Patch p1576 is present
Patch p1577 is present
Patch p1578 is present
Patch p1597 is present
Patch p1598 is present
Patch p1599 is present
Patch p1600 is present
Patch p1601 is present
Patch p1602 is present
Patch p1603 is present
Patch p1604 is present
Patch p1605 is present
Patch p1606 is present
Patch p1607 is present
Patch p1608 is present
Patch p1609 is present
Patch p1610 is present
Patch p1611 is present
Patch p1612 is present
Patch p1687 is present
Patch p1688 is present
Patch p1689 is present
Patch p1690 is present
Patch p1691 is present
Patch p1692 is present
Patch p1693 is present
Patch p1694 is present
Patch p1695 is present
Patch p1696 is present
Patch p1697 is present
Patch p1698 is present
Patch p1699 is present
Patch p1700 is present
Patch p1701 is present
Patch p1702 is present
Patch p1703 is present
Patch p1704 is present
Patch p1718 is present
Patch p1719 is present
Patch p1720 is present
Patch p1721 is present
Patch p1722 is present
Patch p1723 is present
Patch p1724 is present
Patch p1725 is present
Patch p1726 is present
Patch p1727 is present
Patch p1728 is present
Patch p1729 is present
Patch p1730 is present
Patch p1731 is present
Patch p1732 is present
Patch p1733 is present
Patch p1734 is present
Patch p1735 is present
Patch p1736 is present
Patch p1737 is present
Patch p1738 is present
Patch p1739 is present
Patch p1815 is present
Patch p1816 is present
Patch p1817 is present
Patch p1818 is present
Patch p1819 is present
Patch p1820 is present
Patch p1821 is present
Patch p1822 is present
Patch p1823 is present
Patch p1854 is present
Patch p1855 is present
Patch p1856 is present
Patch p1857 is present
Patch p1858 is present
Patch p1859 is present
Patch p1860 is present
Patch p1861 is present
Patch p1862 is present
Patch p1863 is present
Patch p1864 is present
Patch p1865 is present
Patch p1898 is present
Patch p1899 is present
Patch p1900 is present
Patch p1901 is present
Patch p1902 is present
Patch p1903 is present
Patch p1904 is present
Patch p1905 is present
Patch p1906 is present
Patch p1907 is present
Patch p1908 is present
Patch p1909 is present
Patch p1910 is present
Patch p1911 is present
Patch p1912 is present
Patch p1913 is present
Patch p1914 is present
Patch p1915 is present
Patch p1916 is present
Patch p1917 is present
Patch p1958 is present
Patch p1975 is present
Patch p1976 is present
Patch p1977 is present
Patch p1978 is present
Patch p1979 is present
Patch p1980 is present
Patch p2084 is present
Patch p2093 is present
Patch p2094 is present
Patch p2095 is present
Patch p2096 is present
Patch p2097 is present
Patch p2098 is present
Patch p2099 is present
Patch p2100 is present
Patch p2101 is present
Patch p2102 is present
Patch p2103 is present
Patch p2104 is present
Patch p2105 is present
Patch p2106 is present
Patch p2107 is present
Patch p2108 is present
Patch p2109 is present
Patch p2110 is present
Patch p2111 is present
Patch p2112 is present
Patch p2113 is present
Patch p2114 is present
Patch p2115 is present
Patch p2116 is present
Patch p2117 is present
Patch p2129 is present
Patch p2130 is present
Patch p2131 is present
Patch p2132 is present
Patch p2133 is present
Patch p2134 is present
Patch p2135 is present
Patch p2136 is present
Patch p2137 is present
Patch p2138 is present
Patch p2139 is present
Patch p2140 is present
Patch p2141 is present
Patch p2142 is present
Patch p2143 is present
Patch p2144 is present
Patch p2145 is present
Patch p2269 is present
Patch p2270 is present
Patch p2271 is present
Patch p2272 is present
Patch p2273 is present
Patch p2274 is present
Patch p2275 is present
Patch p2276 is present
Patch p2277 is present
Patch p2278 is present
Patch p2279 is present
Patch p2280 is present
Patch p2281 is present
Patch p2282 is present
Patch p2283 is present
Patch p2284 is present
Patch p2285 is present
Patch p2286 is present
Patch p2287 is present
Patch p2288 is present
Patch p2289 is present
Patch p2290 is present
Patch p2291 is present
Patch p2304 is present
Patch p2305 is present
Patch p2306 is present
Patch p2307 is present
Patch p2308 is present
Patch p2309 is present
Patch p2310 is present
Patch p2311 is present
Patch p2312 is present
Patch p2313 is present
Patch p2314 is present
Patch p2331 is present
Patch p2425 is present
Patch p2426 is present
Patch p2427 is present
Patch p2428 is present
Patch p2429 is present
Patch p2430 is present
Patch p2431 is present
Patch p2432 is present
Patch p2433 is present
Patch p2434 is present
Patch p2435 is present
Patch p2436 is present
Patch p2437 is present
Patch p2438 is present
Patch p2439 is present
Patch p2440 is present
Patch p2441 is present
Patch p2442 is present
Patch p2500 is present
Patch p2501 is present
Patch p2502 is present
Patch p2503 is present
Patch p2504 is present
Patch p2505 is present
Patch p2506 is present
Patch p2507 is present
Patch p2508 is present
Patch p2509 is present
Patch p2510 is present
Patch p2511 is present
Patch p2512 is present
Patch p2513 is present
Patch p2514 is present
Patch p2515 is present
Patch p2516 is present
Patch p2517 is present
Patch p2518 is present
Patch p2519 is present
Patch p2520 is present
Patch p2521 is present
Patch p2522 is present
Patch p2523 is present
Patch p2524 is present
Patch p2525 is present
Patch p2526 is present
Patch p2527 is present
Patch p2528 is present
Patch p2529 is present
Patch p2530 is present
Patch p2531 is present
Patch p2532 is present
Patch p2533 is present
Patch p2534 is present
Patch p2535 is present
Patch p2536 is present
Patch p2537 is present
Patch p2538 is present
Patch p2539 is present
Patch p2540 is present
Patch p2541 is present
Patch p2542 is present
Patch p2543 is present
Patch p2544 is present
Patch p2545 is present
Patch p2546 is present
Patch p2547 is present
Patch p2548 is present
Patch p2549 is present
Patch p2550 is present
Patch p2551 is present
Patch p2552 is present
Patch p2553 is present
Patch p2554 is present
Patch p2555 is present
Patch p2556 is present
Patch p2557 is present
Patch p2651 is present
Patch p2762 is present
Patch p2763 is present
Patch p2764 is present
Patch p2765 is present
Patch p2766 is present
Patch p2767 is present
Patch p2768 is present
Patch p2769 is present
Patch p2770 is present
Patch p2771 is present
Patch p2772 is present
Patch p2773 is present
Patch p2774 is present
Patch p2775 is present
Patch p2776 is present
Patch p2777 is present
Patch p2778 is present
Patch p2779 is present
Patch p2780 is present
Patch p2781 is present
Patch p2782 is present
Patch p2783 is present
Patch p2784 is present
Patch p2832 is present
Patch p2840 is present
Patch p2842 is present
Patch p2843 is present
Patch p2844 is present
Patch p2845 is present
Patch p2846 is present
Patch p2847 is present
Patch p2848 is present
Patch p2849 is present
Patch p2871 is present
Patch p2872 is present
Patch p2888 is present
Patch p2891 is present
Patch p2899 is present
Patch p2900 is present
Patch p2901 is present
Patch p2908 is present
Patch p2916 is present
Patch p2924 is present
Patch p2965 is present
Patch p2966 is present
Patch p2979 is present
Patch p2980 is present
Patch p2981 is present
Patch p2994 is present
Patch p2995 is present
Patch p2998 is present
Patch p2999 is present
Patch p3005 is present
Patch p3010 is present
Patch p3011 is present
Patch p3012 is present
Patch p3016 is present
Patch p3020 is present
Patch p3021 is present
Patch p3030 is present
Patch p3033 is present
Patch p3037 is present
Patch p3038 is present
Patch p3063 is present
Patch p3064 is present
Patch p3065 is present
Patch p3077 is present
Patch p3079 is present
Patch p3096 is present
Patch p3103 is present
Patch p3104 is present
Patch p3124 is present
Patch p3125 is present
Patch p3126 is present
Patch p3137 is present
Patch p3138 is present
Patch p3142 is present
Patch p3147 is present
Patch p3148 is present
Patch p3161 is present
Patch p3162 is present
Patch p3186 is present
Patch p3187 is present
Patch p3216 is present
Patch p3217 is present
Patch p3242 is present
Patch p3259 is present
Patch p3260 is present
Patch p3261 is present
Patch p3262 is present
Patch p3282 is present
Patch p3289 is present
Patch p3307 is present
Patch p3308 is present
Patch p3311 is present
Patch p3312 is present
Patch p3383 is present
Patch p3384 is present
Patch p3385 is present
Patch p3386 is present
Patch p3388 is present
Patch p3406 is present
Patch p3407 is present
Patch p3422 is present
Patch p3425 is present
Patch p3427 is present
Patch p3445 is present
Patch p3446 is present
Patch p3447 is present
Patch p3448 is present
Patch p3449 is present
Patch p3461 is present
Patch p3462 is present
Patch p3463 is present
Patch p3464 is present
Patch p3465 is present
Patch p3472 is present
Patch p3473 is present
Patch p3474 is present
Patch p3475 is present
Patch p3476 is present
Patch p3490 is present
Patch p3497 is present
Patch p3498 is present
Patch p3520 is present
Patch p3546 is present
Patch p3547 is present
Patch p3548 is present
Patch p3552 is present
Patch p3553 is present
Patch p3554 is present
Patch p3575 is present
Patch p3576 is present
Patch p3577 is present
Patch p3578 is present
Patch p3579 is present
Patch p3580 is present
Patch p3583 is present
Patch p3606 is present
Patch p3622 is present
Patch p3623 is present
Patch p3624 is present
Patch p3625 is present
Patch p3627 is present
Patch p3628 is present
Patch p3674 is present
Patch p3675 is present
Patch p3676 is present
Patch p3677 is present
Patch p3678 is present
Patch p3679 is present
Patch p3680 is present
Patch p3681 is present
Patch p3691 is present
Patch p3692 is present
Patch p3726 is present
Patch p3743 is present
Patch p3761 is present

In [59]:
all_missing_ids.head()

   origin  patch                                  path
0      -1  p0003  data/ndb_ufes/patch/images/p0003.png
1      -1  p0010  data/ndb_ufes/patch/images/p0010.png
2      -1  p0011  data/ndb_ufes/patch/images/p0011.png
3      -1  p0012  data/ndb_ufes/patch/images/p0012.png
4      -1  p0038  data/ndb_ufes/patch/images/p0038.png

In [60]:
all_missing_ids.to_csv("all_missing_ids.csv", index=False)

# Algorithm