In [6]:
import os

In [9]:
os.chdir("..")

In [10]:
%pwd

'/home/bea/Documents/ndb_ufes_data_organizer'

In [11]:
import pathlib as pl
import pandas as pd

In [12]:
LINKS_PATH = "data/ndb_ufes/link/images"

In [24]:
images_linked = [int(file.name[7:11]) for file in pl.Path(LINKS_PATH).iterdir()]

In [26]:
images_linked = sorted(images_linked)

In [27]:
max_id = max(images_linked)
min_id = min(images_linked)
range_ids = set(range(min_id, max_id + 1))

In [30]:
missing_ids = list(range_ids - set(images_linked))

In [31]:
ids_df = pd.DataFrame({
        "missing_patch_id": missing_ids
    })

In [32]:
ids_df

    missing_patch_id
0                  3
1                 10
2                 12
3                 38
4                 39
..               ...
84               435
85               436
86               437
87               438
88               439

[89 rows x 1 columns]

In [33]:
ids_df["origin"] = -1

In [34]:
ids_df

    missing_patch_id  origin
0                  3      -1
1                 10      -1
2                 12      -1
3                 38      -1
4                 39      -1
..               ...     ...
84               435      -1
85               436      -1
86               437      -1
87               438      -1
88               439      -1

[89 rows x 2 columns]

In [35]:
ids_df.to_csv("missing_ids.csv", index=False)